export type OlvIconType =
'Next' |
'Plus' |
'Delete' |
'ArrowRight' |
'ArrowBottom' |
'Anchor' |
'Calendar' |
'CalendarDisable' |
'File' |
'FileDisable' |
'Folder' |
'FolderDisable' |
'Sort' |
'SortSelect' |
'Filter' |
'FilterSelect' |
'Search' |
'FileSelect' |
'Check' |
'Close' |
'CheckCircle' |
'CheckCircleSelect' |
'CheckCircleSelected' |
'CheckCircleStrong' |
'Crown' |
'CrownDisable' |
'Branches' |
'Lock' |
'Repository' |
'Copy' |
'History' |
'HistorySelect' |
'Reload' |
'Note' |
'Success' |
'Error' |
'QuestionCircle' |
'ArrowNextCircle' |
'Left' |
'Right' |
'Backword' |
'Forward' |
'Project' |
'ProjectSelect' |
'ProjectSelected' |
'List' |
'ListSelect' |
'ListSelected' |
'FileList' |
'AuditList' |
'MoreDisable' |
'More' |
'Reload_b' |
'ReloadSelect_b' |
'Home_b' |
'HomeSelect_b' |
'Project_b' |
'ProjectSelect_b' |
'Profile_b' |
'ProfileSelect_b' |
'Stamp_b' |
'StampSelect_b' |
'FileList_b' |
'FileListSelect_b' |
'DownloadDisable_b' |
'Download_b' |
'Arrow_w' |
'Plus_w' |
'Search_w' |
'Prev_w' |
'Next_w'|
'CodeShowIcon'|
'CodeCopyIcon'
